In [16]:
import os
import pandas as pd

In [17]:
data_path = "data/20_newsgroups"

In [18]:
documents = []
labels = []

for category in os.listdir(data_path):
    
    category_path = os.path.join(data_path, category)
    
    if os.path.isdir(category_path):
        
        for file in os.listdir(category_path):
            
            file_path = os.path.join(category_path, file)
            
            with open(file_path, "r", encoding="latin1") as f:
                
                documents.append(f.read())
                labels.append(category)

print("Total documents:", len(documents))
print("Total categories:", len(set(labels)))

PermissionError: [Errno 13] Permission denied: 'data/20_newsgroups\\20_newsgroups\\alt.atheism'

In [20]:
import os
os.getcwd()

'C:\\Users\\naush\\semantic-search-system'

In [5]:
os.listdir()

['.ipynb_checkpoints', 'data', 'dataset_loading.ipynb', 'venv']

In [6]:
os.listdir("data")

['20newsgroups.data.html',
 '20newsgroups.html',
 '20_newsgroups.tar.gz',
 'mini_newsgroups',
 'mini_newsgroups.tar.gz',
 'venv']

In [7]:
import tarfile

tar = tarfile.open("20_newsgroups.tar.gz", "r:gz")
tar.extractall()
tar.close()

print("Extraction completed")

FileNotFoundError: [Errno 2] No such file or directory: '20_newsgroups.tar.gz'

In [8]:
import tarfile

tar = tarfile.open("mini_newsgroups.tar.gz", "r:gz")
tar.extractall()
tar.close()

print("Extraction completed")

FileNotFoundError: [Errno 2] No such file or directory: 'mini_newsgroups.tar.gz'

In [9]:
os.listdir()

['.ipynb_checkpoints', 'data', 'dataset_loading.ipynb', 'venv']

In [10]:
import tarfile

file_path = "./20_newsgroups.tar.gz"

with tarfile.open(file_path, "r:gz") as tar:
    tar.extractall()

print("Extraction completed")

FileNotFoundError: [Errno 2] No such file or directory: './20_newsgroups.tar.gz'

In [11]:
import os
os.listdir()

['.ipynb_checkpoints', 'data', 'dataset_loading.ipynb', 'venv']

In [12]:
import os
os.listdir("data")

['20newsgroups.data.html',
 '20newsgroups.html',
 '20_newsgroups',
 '20_newsgroups.tar.gz',
 'mini_newsgroups',
 'mini_newsgroups.tar.gz',
 'venv']

In [13]:
data_path = "data/20_newsgroups"

In [14]:
import os

documents = []
labels = []

for category in os.listdir(data_path):

    category_path = os.path.join(data_path, category)

    if os.path.isdir(category_path):

        for file in os.listdir(category_path):

            file_path = os.path.join(category_path, file)

            with open(file_path, "r", encoding="latin1") as f:
                documents.append(f.read())
                labels.append(category)

print("Total documents:", len(documents))
print("Total categories:", len(set(labels)))

PermissionError: [Errno 13] Permission denied: 'data/20_newsgroups\\20_newsgroups\\alt.atheism'

In [21]:
data_path = "data/20_newsgroups/20_newsgroups"

In [23]:
import os

data_path = "data/20_newsgroups/20_newsgroups"

documents = []
labels = []

for category in os.listdir(data_path):

    category_path = os.path.join(data_path, category)

    if os.path.isdir(category_path):

        for file in os.listdir(category_path):

            file_path = os.path.join(category_path, file)

            with open(file_path, "r", encoding="latin1") as f:
                documents.append(f.read())
                labels.append(category)

print("Total documents:", len(documents))
print("Total categories:", len(set(labels)))

Total documents: 19997
Total categories: 20

In [24]:
import pandas as pd

df = pd.DataFrame({
    "text": documents,
    "category": labels
})

df.head()

                                                text     category
0  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:49...  alt.atheism
1  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism
2  Newsgroups: alt.atheism\nPath: cantaloupe.srv....  alt.atheism
3  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism
4  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism

In [25]:
import re

In [26]:
def clean_text(text):
    
    # Remove email headers (everything before the first blank line)
    text = re.split(r"\n\n", text, maxsplit=1)[-1]

    # Remove email addresses
    text = re.sub(r"\S+@\S+", "", text)

    # Remove special characters
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [21]:
df["clean_text"] = df["text"].apply(clean_text)

In [22]:
print("BEFORE CLEANING:\n")
print(df["text"][0][:500])

print("\n\nAFTER CLEANING:\n")
print(df["clean_text"][0][:500])

BEFORE CLEANING:

Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:49960 alt.atheism.moderated:713 news.answers:7054 alt.answers:126
Path: cantaloupe.srv.cs.cmu.edu!crabapple.srv.cs.cmu.edu!bb3.andrew.cmu.edu!news.sei.cmu.edu!cis.ohio-state.edu!magnus.acs.ohio-state.edu!usenet.ins.cwru.edu!agate!spool.mu.edu!uunet!pipex!ibmpcug!mantis!mathew
From: mathew <mathew@mantis.co.uk>
Newsgroups: alt.atheism,alt.atheism.moderated,news.answers,alt.answers
Subject: Alt.Atheism FAQ: Atheist Resources
Summary: Books, addresses, mu


AFTER CLEANING:

Archive name atheism resources Alt atheism archive name resources Last modified 11 December 1992 Version 1 0 Atheist Resources Addresses of Atheist Organizations USA FREEDOM FROM RELIGION FOUNDATION Darwin fish bumper stickers and assorted other atheist paraphernalia are available from the Freedom From Religion Foundation in the US Write to FFRF P O Box 750 Madison WI 53701 Telephone 608 256 8900 EVOLUTION DESIGNS Evolution Designs sell the Darwin fish It s a fish symbol like the ones Christians

In [23]:
df.shape

(19997, 3)

In [24]:
from sentence_transformers import SentenceTransformer

In [30]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [35]:
embeddings = model.encode(
    df["clean_text"].tolist(),
    show_progress_bar=True
)

KeyError: 'clean_text'

In [27]:
import numpy as np

embeddings = np.array(embeddings)

print("Embedding shape:", embeddings.shape)

Embedding shape: (19997, 384)

In [29]:
df["embedding"] = embeddings.tolist()

# text
# category
# clean_text
# embedding

# Sentence Transformers convert documents into dense vector
# representations that capture semantic meaning. These embeddings
# allow efficient similarity search and clustering in vector space.

In [32]:
# Step 7 — Build the Vector Database (FAISS)
import faiss
import numpy as np

In [31]:
embedding_matrix = np.array(embeddings).astype("float32")

NameError: name 'embeddings' is not defined

In [32]:
embedding_matrix.shape

(19997, 384)

In [36]:
# Create FAISS Index
# IndexFlatL2 → exact similarity search using Euclidean distance
# dimension → embedding size (384)

dimension = embedding_matrix.shape[1]

index = faiss.IndexFlatL2(dimension)

NameError: name 'embedding_matrix' is not defined

In [34]:
index.add(embedding_matrix)

In [35]:
# Add Vectors to FAISS
print("Total vectors in index:", index.ntotal)

Total vectors in index: 19997

In [36]:
query = "space mission launch satellite"

query_embedding = model.encode([query]).astype("float32")

k = 5

distances, indices = index.search(query_embedding, k)

In [37]:
# 7.6 Display Results
# FAISS is used as a vector index to efficiently perform
# nearest-neighbour search over document embeddings.
# This enables semantic retrieval based on meaning rather
# than keyword matching.

for i in indices[0]:
    print("Category:", df.iloc[i]["category"])
    print(df.iloc[i]["clean_text"][:200])
    print("-----")

Category: sci.space
Date Tue 6 Apr 1993 15 40 47 GMT I need as much information about Cosmos 2238 and its rocket fragment 1993 018B as possible Both its purpose launch date location in short EVERYTHING Can you help Tony
-----
Category: sci.space
In article Henry Spencer writes In article David M Palmer writes orbiting billboard I would just like to point out that it is much easier to place an object at orbital altitude than it is to place it
-----
Category: sci.space
I can tell you that when AMSAT launched some birds along a Spot satellite French that during installation of some instruments on Spot 2 there heavily armed legionaires who had a take no prisoners look
-----
Category: sci.space
Bill Higgins Beam Jockey writes In article writes COMMERCIAL SPACE NEWS SPACE TECHNOLOGY INVESTOR NUMBER 22 Other commercial launch site ventures including those at Woomera Poker Flat Cape York White
-----
Category: sci.space
ARIANESPACE FLIGHT 56 Flight V 56 was originally intended to carry the Hughes HS 601 series Galaxy IV satellite but the payload was withdrawn just prior to flight The 56th Ariane launch is now schedul
-----

In [38]:
# Step 8 — Fuzzy Clustering of Documents

!pip install scikit-fuzzy

Requirement already satisfied: scikit-fuzzy in .\venv\Lib\site-packages (0.5.0)

In [39]:
import skfuzzy as fuzz

In [40]:
# 8.3 Prepare Data for Clustering
# Fuzzy C-Means expects data in feature × samples format.We must transpose them.

X = embedding_matrix.T

In [41]:
print(X.shape)

(384, 19997)

In [42]:
n_clusters = 12

In [43]:
cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(
    X,
    c=n_clusters,
    m=2,
    error=0.005,
    maxiter=1000,
    init=None
)

In [44]:
u

array([[0.08333381, 0.08333406, 0.08333373, ..., 0.08333405, 0.08333425,
        0.08333369],
       [0.08333321, 0.08333313, 0.08333323, ..., 0.08333313, 0.08333305,
        0.08333325],
       [0.08333313, 0.08333304, 0.08333316, ..., 0.08333302, 0.0833329 ,
        0.08333313],
       ...,
       [0.08333299, 0.0833328 , 0.08333309, ..., 0.08333285, 0.08333274,
        0.08333316],
       [0.0833323 , 0.08333185, 0.08333241, ..., 0.08333179, 0.08333172,
        0.08333262],
       [0.08333406, 0.08333443, 0.08333389, ..., 0.08333439, 0.08333464,
        0.08333379]], shape=(12, 19997))

In [45]:
(n_clusters, num_documents)

NameError: name 'num_documents' is not defined

In [46]:
print(u.shape)

(12, 19997)

In [47]:
# 8.7 Assign Dominant Cluster

cluster_labels = np.argmax(u, axis=0)

In [48]:
cluster_labels[:10]

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [49]:
# 8.8 Add Cluster Labels to DataFrame

df["cluster"] = cluster_labels

In [50]:
df.head()

,text,category,clean_text,embedding,cluster
0,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:49...,alt.atheism,Archive name atheism resources Alt atheism arc...,"[-0.0285569429397583, 0.016917048022150993, -0...",6
1,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...,alt.atheism,Archive name atheism introduction Alt atheism ...,"[-0.027238793671131134, -0.04237806797027588, ...",6
2,Newsgroups: alt.atheism\nPath: cantaloupe.srv....,alt.atheism,In article Charley Wingate writes Well John ha...,"[-0.09503985196352005, -0.004863628186285496, ...",6
3,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...,alt.atheism,until kings become philosophers or philosopher...,"[-0.033383529633283615, 0.044307440519332886, ...",6
4,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...,alt.atheism,In article Bob McGwier writes 1 HOWEVER I hate...,"[-0.02208806946873665, 0.06549318879842758, -0...",6

In [51]:
df["cluster"].value_counts()

cluster
6     9867
10    8027
7     1651
3      254
0      113
11      39
2       18
4       14
9       12
5        1
1        1
Name: count, dtype: int64

In [2]:
import numpy as np
from sentence_transformers import SentenceTransformer

In [3]:
# Fuzzy C-Means clustering is applied to the document embeddings
# to discover latent semantic groups within the dataset.

# Unlike hard clustering algorithms such as K-Means,
# Fuzzy C-Means assigns membership probabilities to each
# document across clusters, allowing documents to belong
# to multiple semantic themes simultaneously.


semantic_cache = {}

In [3]:
{
  query_embedding : search_results
}

NameError: name 'query_embedding' is not defined

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
# 9.3 Build Cache Search Function

# Create a function to check if a similar query already exists.

def check_cache(query_embedding, threshold=0.90):

    for cached_query, cached_result in semantic_cache.items():

        similarity = cosine_similarity(
            [query_embedding],
            [cached_query]
        )[0][0]

        if similarity > threshold:
            return cached_result

    return None

In [6]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [7]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [12]:
print(model)

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [11]:
model.encode(["space shuttle mission"])

array([[ 4.80819214e-03, -1.68409804e-03, -3.79324332e-02,
         1.45229530e-02, -7.44499862e-02, -1.62368976e-02,
         7.86334053e-02, -2.18448155e-02,  5.48836589e-03,
        -1.33092189e-02, -2.20028367e-02,  2.02864539e-02,
         1.31824063e-02, -1.10626984e-02, -2.69972831e-02,
        -1.24883000e-02,  6.51932359e-02, -6.81476714e-03,
        -4.14763875e-02, -6.11192323e-02,  3.92902817e-04,
         1.22798001e-02, -2.46473104e-02,  6.86390772e-02,
        -3.56159210e-02,  6.47558719e-02,  4.92868163e-02,
        -6.31355420e-02, -5.60103282e-02, -4.72414568e-02,
        -9.81409755e-03,  3.59761193e-02,  7.56186917e-02,
         4.10142541e-02,  6.51928708e-02,  1.23051487e-01,
         1.34600443e-03, -4.19883057e-02,  1.54162794e-02,
        -1.00162067e-01, -5.18786646e-02, -8.33146423e-02,
         6.79359287e-02,  4.22359593e-02, -8.93923827e-03,
        -4.12749723e-02, -2.67390534e-02, -7.68720582e-02,
         1.46500096e-01,  3.16821150e-02, -3.74349691e-02,
        -1.43958852e-02, -5.23214899e-02, -5.07384129e-02,
         6.42942488e-02,  1.33028831e-02, -5.43154106e-02,
        -8.53605643e-02,  4.19928767e-02, -7.26163089e-02,
        -3.69376019e-02, -7.27878138e-02,  1.67824342e-04,
         6.10316806e-02,  2.67844144e-02, -9.22555011e-03,
        -2.74230260e-03, -1.08648263e-01,  1.17344558e-01,
        -1.22521281e-01, -4.28446867e-02,  5.17967977e-02,
        -8.77298489e-02, -1.01252742e-01,  7.42843375e-03,
        -1.21106459e-02,  4.88741659e-02,  7.56029785e-02,
         2.37277020e-02, -4.22134101e-02,  5.50498925e-02,
        -6.27538040e-02, -8.09638947e-02,  5.46811633e-02,
        -4.21813577e-02, -7.11011291e-02, -1.03345569e-02,
         3.90669284e-03,  2.40953341e-02,  8.62553194e-02,
         1.84714925e-02, -2.87513360e-02,  7.38666356e-02,
         1.87280960e-02, -1.50889471e-01, -5.31274965e-03,
        -7.21731037e-02, -5.29489480e-02,  2.84459349e-02,
         1.14059806e-01,  4.39756475e-02,  2.57066730e-02,
         7.48636853e-03, -2.46363226e-02, -4.96505350e-02,
        -6.62162006e-02,  1.32389022e-02, -8.96338653e-03,
         4.69739698e-02, -6.69513643e-02, -2.24218946e-02,
        -2.50396729e-02,  3.26771699e-02,  6.53614029e-02,
        -5.22857495e-02, -2.13160869e-02, -2.85824910e-02,
         1.26829585e-02, -2.45204807e-04, -3.20532620e-02,
        -2.14477107e-02, -4.60461080e-02,  5.75975366e-02,
        -1.30078876e-02, -1.26657858e-01,  8.73336394e-04,
         6.76393062e-02, -1.22919268e-33,  1.11340836e-03,
        -8.06445479e-02,  5.48339449e-02,  1.09661989e-01,
         8.58472846e-03,  1.67826489e-02, -7.19824880e-02,
        -2.09680870e-02, -4.61730585e-02, -5.65232225e-02,
        -9.21388064e-03, -5.27984127e-02,  7.80656096e-03,
        -2.14880388e-02,  4.04920280e-02, -3.22426967e-02,
        -4.12619635e-02,  5.26722008e-03,  2.87314858e-02,
        -4.54239435e-02, -2.25356650e-02, -2.46929768e-02,
        -4.26531248e-02, -1.09491674e-02,  1.20356657e-01,
         3.39002050e-02, -2.73146667e-02, -4.19108011e-02,
        -3.37334126e-02,  4.98344414e-02, -7.73470700e-02,
         6.93681985e-02, -1.36329178e-02,  2.45002490e-02,
         7.92577118e-02,  4.58761267e-02, -6.47892244e-03,
        -2.53292937e-02, -2.64397543e-02,  5.30974828e-02,
        -6.52376711e-02,  1.29489610e-02, -3.32068317e-02,
         3.91211212e-02,  7.56367669e-02, -1.22962808e-02,
         4.75096665e-02, -2.55781338e-02,  1.11822613e-01,
         1.41706318e-01,  8.87172669e-03, -4.03112732e-03,
         2.36922484e-02, -4.45674509e-02,  6.60897940e-02,
         5.73243340e-03,  5.15608825e-02,  2.33318228e-02,
         7.93028157e-03,  4.72163334e-02,  4.66328487e-03,
         6.73735142e-03,  2.65740603e-02,  3.41123086e-03,
         1.56115785e-01,  8.41840059e-02, -3.72989364e-02,
        -1.13048488e-02,  2.27347761e-02,  4.89421673e-02,
        -4.21464294e-02,  9.03202686e-03,  6.66332692e-02,
        -3.34940180e-02,  3.24606299e-02, -1.05728190e-02,
         1.54429739e-02,  2.69491542e-02, -5.52491881e-02,
         2.77738702e-02, -8.57432000e-03, -2.61406098e-02,
         1.96093172e-02,  3.63679715e-02,  5.24000302e-02,
        -3.93688232e-02, -2.79695541e-02, -1.06233545e-02,
         3.67158093e-02, -2.48511229e-02, -1.25493214e-01,
         4.46841680e-03, -4.82353792e-02,  7.66204372e-02,
         1.94371268e-02, -9.50498304e-35,  3.18240747e-02,
         5.39711416e-02,  1.58266760e-02,  1.38047040e-02,
        -8.55476223e-03, -2.10483819e-02, -9.26083513e-03,
        -4.91138687e-03, -5.20815738e-02,  1.02559693e-01,
        -3.37434225e-02,  8.90118256e-03,  7.40775540e-02,
        -1.82173401e-02, -1.49390204e-02,  3.68649475e-02,
         1.04180515e-01, -7.07445573e-03, -8.50993618e-02,
         5.17681353e-02,  2.00529844e-02,  3.85203287e-02,
        -7.10400268e-02, -2.64854655e-02,  2.44137626e-02,
         2.95551587e-02,  1.07446566e-01,  1.64713375e-02,
        -3.70177925e-02,  1.89653877e-02,  7.22451583e-02,
         3.08140740e-02,  1.03976568e-02,  4.11784612e-02,
        -3.73957269e-02,  6.64944351e-02,  6.63558319e-02,
         6.68212175e-02, -2.16565896e-02,  3.50926234e-03,
         4.23760712e-03, -4.31398489e-02, -1.93877108e-02,
         7.09189475e-02, -4.72129323e-02, -2.89658122e-02,
         7.75982812e-02,  5.91789410e-02, -1.17506105e-02,
         3.00108101e-02, -9.77932662e-02, -1.41101442e-02,
        -3.61686759e-02,  2.38446845e-03,  3.63215134e-02,
        -3.70630585e-02, -5.02410829e-02,  1.09911570e-02,
         7.11301640e-02, -3.64714861e-02,  6.01035692e-02,
         1.48018254e-02,  3.48616615e-02, -2.21136007e-02,
        -7.91716129e-02, -3.60779129e-02,  5.11649214e-02,
         9.06273648e-02, -1.33443326e-01,  6.23578541e-02,
         3.06461807e-02, -5.11177592e-02,  2.12959461e-02,
         5.16290367e-02,  1.35713385e-03,  4.50342137e-04,
         1.83821712e-02, -3.65721621e-02, -2.62645930e-02,
         5.03519997e-02,  9.01822094e-03, -3.20896804e-02,
        -3.12873535e-02,  5.47862612e-02, -9.31571890e-03,
         5.49075231e-02, -1.26073724e-02,  1.66685041e-02,
        -1.11203520e-02, -1.59849413e-02, -5.43391407e-02,
        -1.99582428e-02,  7.15125492e-03,  3.08032497e-03,
        -4.46274783e-03, -1.50110644e-08, -1.99268423e-02,
         5.84695451e-02, -3.66605930e-02, -2.63515338e-02,
         2.48193741e-02, -3.08550727e-02, -4.01485451e-02,
         6.44650357e-03, -4.19234335e-02, -4.03616205e-02,
         4.91661066e-03,  1.39151951e-02, -3.90000753e-02,
         8.13356414e-02, -9.37144179e-03,  7.15912599e-03,
         2.33730627e-03, -3.13919224e-02, -1.72975659e-02,
        -6.86330274e-02, -5.05049303e-02, -1.84264313e-02,
         1.30377710e-01, -6.87868074e-02, -3.82954888e-02,
         3.93313020e-02,  3.65188494e-02,  1.40469940e-02,
         7.93809369e-02, -4.73941378e-02,  1.04343034e-02,
        -1.06752012e-02, -7.83324689e-02,  1.67230703e-02,
        -5.76685928e-02,  1.11133195e-02,  4.95465146e-03,
         5.66942282e-02,  1.77665502e-02, -9.04722232e-03,
        -2.25875843e-02,  8.35362449e-02,  7.42757041e-03,
         3.71944569e-02, -5.35356142e-02,  1.38529420e-01,
        -3.77183445e-02, -4.04415466e-03, -1.21268578e-01,
        -6.33065552e-02, -3.96228358e-02, -2.07476858e-02,
        -5.70765920e-02,  5.96529208e-02,  2.59266421e-02,
         5.70972376e-02,  8.87295790e-03, -3.08757871e-02,
         2.49774032e-03,  1.97751466e-02, -2.27027666e-02,
         2.57061105e-02, -1.28854081e-01, -7.92072117e-02]], dtype=float32)

In [12]:
results = semantic_search("space shuttle launch mission")
print(results)

NameError: name 'index' is not defined

In [28]:
print(df.shape)
df.head()

(19997, 2)

                                                text     category
0  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:49...  alt.atheism
1  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism
2  Newsgroups: alt.atheism\nPath: cantaloupe.srv....  alt.atheism
3  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism
4  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism

In [29]:
model.encode(["hello world"])

array([[-3.44772041e-02,  3.10232397e-02,  6.73496863e-03,
         2.61089690e-02, -3.93619612e-02, -1.60302460e-01,
         6.69239312e-02, -6.44147955e-03, -4.74505574e-02,
         1.47589119e-02,  7.08753690e-02,  5.55275641e-02,
         1.91933755e-02, -2.62513272e-02, -1.01095000e-02,
        -2.69405413e-02,  2.23074704e-02, -2.22266559e-02,
        -1.49692699e-01, -1.74930841e-02,  7.67624797e-03,
         5.43522798e-02,  3.25447368e-03,  3.17259766e-02,
        -8.46213549e-02, -2.94059906e-02,  5.15956245e-02,
         4.81240302e-02, -3.31479218e-03, -5.82792051e-02,
         4.19693030e-02,  2.22106855e-02,  1.28188848e-01,
        -2.23389659e-02, -1.16563011e-02,  6.29283339e-02,
        -3.28762829e-02, -9.12260562e-02, -3.11753899e-02,
         5.26995622e-02,  4.70348559e-02, -8.42030272e-02,
        -3.00562084e-02, -2.07447819e-02,  9.51781124e-03,
        -3.72180226e-03,  7.34334765e-03,  3.93243358e-02,
         9.32740942e-02, -3.78861465e-03, -5.27421273e-02,
        -5.80582172e-02, -6.86439546e-03,  5.28320158e-03,
         8.28929767e-02,  1.93627197e-02,  6.28447579e-03,
        -1.03307618e-02,  9.03236400e-03, -3.76836807e-02,
        -4.52060923e-02,  2.40163747e-02, -6.94418000e-03,
         1.34915914e-02,  1.00054979e-01, -7.16838986e-02,
        -2.16950327e-02,  3.16185318e-02, -5.16346544e-02,
        -8.22477415e-02, -6.56933337e-02, -9.89541225e-03,
         5.81640890e-03,  7.35545754e-02, -3.40503044e-02,
         2.48860680e-02,  1.44880479e-02,  2.64574029e-02,
         9.65677015e-03,  3.02172918e-02,  5.28040081e-02,
        -7.53598958e-02,  9.89719853e-03,  2.98368782e-02,
         1.75555926e-02,  2.30919998e-02,  1.93390297e-03,
         1.40016479e-03, -4.71759848e-02, -1.11944070e-02,
        -1.14201397e-01, -1.98120363e-02,  4.02662419e-02,
         2.19301041e-03, -7.97922313e-02, -2.53823288e-02,
         9.44829434e-02, -2.89811157e-02, -1.45002499e-01,
         2.30977491e-01,  2.77310777e-02,  3.21114995e-02,
         3.10650431e-02,  4.28328477e-02,  6.42378330e-02,
         3.21632139e-02, -4.87670302e-03,  5.56994006e-02,
        -3.75323705e-02, -2.15055868e-02, -2.83426996e-02,
        -2.88469195e-02,  3.83531526e-02, -1.74686499e-02,
         5.24853356e-02, -7.48760775e-02, -3.12597044e-02,
         2.18415540e-02, -3.98956202e-02, -8.58708471e-03,
         2.69566234e-02, -4.84955385e-02,  1.14698987e-02,
         2.96182632e-02, -2.05722116e-02,  1.31039191e-02,
         2.88333893e-02, -3.19420129e-33,  6.47820458e-02,
        -1.81301795e-02,  5.17899506e-02,  1.21982791e-01,
         2.87801232e-02,  8.72198120e-03, -7.05211833e-02,
        -1.69072617e-02,  4.07397710e-02,  4.21162024e-02,
         2.54472531e-02,  3.57461870e-02, -4.91447337e-02,
         2.12905183e-03, -1.55466273e-02,  5.07305637e-02,
        -4.81852852e-02,  3.58805880e-02, -4.06715414e-03,
         1.01724744e-01, -5.59700057e-02, -1.06810592e-02,
         1.12357801e-02,  9.06864777e-02,  4.23453096e-03,
         3.51386666e-02, -9.70285200e-03, -9.38652307e-02,
         9.28555951e-02,  8.00493266e-03, -7.70542631e-03,
        -5.20866886e-02, -1.25879217e-02,  3.26687028e-03,
         6.01351913e-03,  7.58164283e-03,  1.05171548e-02,
        -8.63455310e-02, -6.98787570e-02, -2.53388588e-03,
        -9.09766257e-02,  4.68873419e-02,  5.20764962e-02,
         7.19386339e-03,  1.09036379e-02, -5.22951875e-03,
         1.39373373e-02,  2.19683889e-02,  3.42085622e-02,
         6.02246299e-02,  1.16613068e-04,  1.47319958e-02,
        -7.00891837e-02,  2.84990147e-02, -2.76016109e-02,
         1.07683530e-02,  3.48309502e-02, -2.24879216e-02,
         9.76907089e-03,  7.72278309e-02,  2.15883274e-02,
         1.14956230e-01, -6.80011362e-02,  2.37610061e-02,
        -1.59839205e-02, -1.78269576e-02,  6.43948913e-02,
         3.20257507e-02,  5.02702110e-02, -5.91369439e-03,
        -3.37079801e-02,  1.78403482e-02,  1.65733974e-02,
         6.32965341e-02,  3.46772186e-02,  4.64734361e-02,
         9.79061723e-02, -6.63550152e-03,  2.52070203e-02,
        -7.79883415e-02,  1.69264060e-02, -9.45846841e-04,
         2.24718601e-02, -3.82532589e-02,  9.57047418e-02,
        -5.35076205e-03,  1.04690483e-02, -1.15240566e-01,
        -1.32625243e-02, -1.07094077e-02, -8.31172541e-02,
         7.32736215e-02,  4.93921824e-02, -8.99441261e-03,
        -9.58455503e-02,  3.36615077e-33,  1.24931827e-01,
         1.93497110e-02, -5.82257397e-02, -3.59881930e-02,
        -5.07467762e-02, -4.56624106e-02, -8.26034024e-02,
         1.48194805e-01, -8.84211436e-02,  6.02744520e-02,
         5.10302559e-02,  1.03030875e-02,  1.41214237e-01,
         3.08138635e-02,  6.10330701e-02, -5.28513156e-02,
         1.36648864e-01,  9.18991584e-03, -1.73252560e-02,
        -1.28486473e-02, -7.99524970e-03, -5.09800501e-02,
        -5.23506477e-02,  7.59303756e-03, -1.51662026e-02,
         1.69603173e-02,  2.12705452e-02,  2.05579847e-02,
        -1.20028108e-01,  1.44618321e-02,  2.67598629e-02,
         2.53305901e-02, -4.27546315e-02,  6.76851766e-03,
        -1.44586349e-02,  4.52619866e-02, -9.14766043e-02,
        -1.94391888e-02, -1.78335346e-02, -5.49101569e-02,
        -5.26411086e-02, -1.04590338e-02, -5.20160273e-02,
         2.08919868e-02, -7.99703225e-02, -1.21112820e-02,
        -5.77314384e-02,  2.31781825e-02, -8.03157128e-03,
        -2.59893034e-02, -7.99567327e-02, -2.07287949e-02,
         4.88177240e-02, -2.03892216e-02, -4.91765924e-02,
         1.41596189e-02, -6.36221319e-02, -7.80738145e-03,
         1.64315253e-02, -2.56825387e-02,  1.33810723e-02,
         2.62487829e-02,  9.97840241e-03,  6.32289648e-02,
         2.67208554e-03, -6.58276817e-03,  1.66319814e-02,
         3.23665179e-02,  3.79424766e-02, -3.63760404e-02,
        -6.91094715e-03,  1.59763047e-04, -1.63353526e-03,
        -2.72782221e-02, -2.80380677e-02,  4.96815667e-02,
        -2.88671665e-02, -2.41804589e-03,  1.47749363e-02,
         9.76459123e-03,  5.79755194e-03,  1.34860976e-02,
         5.56785893e-03,  3.72271165e-02,  7.23254215e-03,
         4.01562266e-02,  8.15032050e-02,  7.19916224e-02,
        -1.30561702e-02, -4.28819992e-02, -1.10112187e-02,
         4.89776861e-03, -9.22971964e-03,  3.51914763e-02,
        -5.10350130e-02, -1.57143756e-08, -8.86244252e-02,
         2.39093564e-02, -1.62387732e-02,  3.17005143e-02,
         2.72841845e-02,  5.24687953e-02, -4.70709391e-02,
        -5.88474199e-02, -6.32082522e-02,  4.08885218e-02,
         4.98279408e-02,  1.06551662e-01, -7.45023265e-02,
        -1.24954870e-02,  1.83706190e-02,  3.94740961e-02,
        -2.47978196e-02,  1.45162391e-02, -3.70691828e-02,
         2.00156868e-02, -4.85999190e-05,  9.86657850e-03,
         2.48387847e-02, -5.24580777e-02,  2.93141641e-02,
        -8.71919468e-02, -1.44997947e-02,  2.60190517e-02,
        -1.87464021e-02, -7.62051865e-02,  3.50433253e-02,
         1.03639528e-01, -2.80505158e-02,  1.27182314e-02,
        -7.63254985e-02, -1.86524168e-02,  2.49766745e-02,
         8.14454406e-02,  6.87588900e-02, -6.40566349e-02,
        -8.38938951e-02,  6.13624230e-02, -3.35455760e-02,
        -1.06153391e-01, -4.00805324e-02,  3.25302109e-02,
         7.66248256e-02, -7.30161369e-02,  3.37625504e-04,
        -4.08715941e-02, -7.57885277e-02,  2.75276843e-02,
         7.46254548e-02,  1.77172609e-02,  9.12184119e-02,
         1.10220164e-01,  5.69813477e-04,  5.14633469e-02,
        -1.45512661e-02,  3.32320072e-02,  2.37922929e-02,
        -2.28898395e-02,  3.89375500e-02,  3.02068368e-02]], dtype=float32)